import numpy as np
from matplotlib import pyplot as plt

 # random seeds generated by runman (replaced <seeds>)
try:
    random.seed(971907)
except NameError:
    pass # random is not imported and used
try:
    np.random.seed(971907)
except NameError:
    pass # random is not imported and used
try:
    tf.set_random_seed(971907)
except NameError:
    pass # random is not imported and used

# configurations generated by runman (replaced <config>) 
w = 0.5 
noise = 2 


# from configs, we now have the vars w and noise
w = np.array(w)
x = np.arange(0, 100, 1)
y = w*x + np.random.normal(0, noise, 100)

plt.plot(x, y)
plt.savefig('plot.png')